### ISSUE TITLE
Hold up `CommandRequest`s until new tick has passed

### ISSUE THREAD

**Issue by Belissimo-T** [seekers-dev/seekers-server#86]

**Comment by Kiyotoko** [comment]
This was added with [41d7e5a](https://github.com/seekers-dev/seekers-server/commit/41d7e5a19287fa9a5dd9b7b61c834dfad0e8866e). However, as it has not yet been tested, the issue will remain open until then.

**Comment by Kiyotoko** [comment]
As this feature was now tested over a week without any problems, this issue is now closed.
